services:

  app:
    build: ./app/
    environment:
      - PORT=8989
    networks: 
      - count_app
    env_file:
      - ./app/appdbpass.env
    volumes:
      - ./app/app_logs:/var/log/count_app/
    depends_on:
      - db
    deploy:
      replicas: 3

  db:
    image: "mysql:9.0.1"
    networks:
      - count_app
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/init/:/docker-entrypoint-initdb.d/
    env_file:
      - ./db/dbpass.env
    command:
      mysqld --general-log=1 --general-log-file=/var/log/mysql/general_log.log


  nginx: 
    build: ./nginx/
    container_name: nginx_lb
    ports:
      - "80:80"
    networks:
      - count_app
    depends_on:
      - app
      - db 
  
networks:
  count_app:
    name: count_app
    driver: bridge
