services:

  app:
    build: ./app/
    networks: 
      - count_app
    volumes:
      - ./app/app_logs/logs.log:/var/log/count_app.log
    deploy:
      replicas: 3

  db:
    build: ./db/
    container_name: mysql_db
    ports:
      - "3306:3306"
    networks:
      - count_app
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql

  nginx: 
    build: ./nginx/
    container_name: nginx_lb
    ports:
      - "80:80"
    networks:
      - count_app
    depends_on:
      - app
      - db 
  
networks:
  count_app:  
