name: Build app CI

on:
  push:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    - name: config aws cred
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: login to ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: build  and push to ecr
      run:  | 
            IMAGE_TAG="count_app-${{ github.ref_name }}-$(git rev-parse --short $GITHUB_SHA)"
            echo ${{ vars.ECR_REPO }}:$IMAGE_TAG && docker build --no-cache -t ${{ vars.ECR_REPO }}:latest -t ${{ vars.ECR_REPO }}:$IMAGE_TAG ./app/
            docker push ${{ vars.ECR_REPO }} --all-tags
      

  
  
