name: Build app CI

on:
  push:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    - name: config aws cred
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: build docker image out of app
      run:  IMAGE_TAG="count_app-${{ github.ref_name }}-$(git rev-parse --short $GITHUB_SHA):latest" && \
            echo ${{ vars.ECR_REPO }}:$IMAGE_TAG && docker build --no-cache -t $ECR_REPO:$IMAGE_TAG ./app/ && \
            docker push ${{ vars.ECR_REPO }}:$IMAGE_TAG
      

  
  
