name: Build app CI

on:
  push:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: config aws cred
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: set IMAGE_TAG
      run: IMAGE_TAG="count_app-$GITHUB_REF-$(git rev-parse --short $GITHUB_SHA)" && echo $IMAGE_TAG
    
    - uses: actions/checkout@v4
    - name: build docker image out of app
      run:  docker build --no-cache -t $ECR_REPO:$IMAGE_TAG ./app/ && \
           docker push $ECR_REPO:$IMAGE_TAG
      

  
  
